export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as AllDrugsPage } from './AllDrugsPage'
export { default as ShopPage } from './ShopPage'
export { default as StatisticsPage } from './StatisticsPage'
export { default as CreateShopPage } from './CreateShopPage'
export { default as EditShopPage } from './EditShopPage'
export { default as MedicinePage } from './MedicinePage'
export { default as CardMyShopPage } from './CardMyShopPage'
export { default as DescriptionPage } from './DescriptionPage'
export { default as ReviewsPage } from './ReviewsPage'
export { default as NotFoundPage } from './NotFoundPage'
// export { default as SharedLayout } from '../shared/components/SharedLayout/'
